// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAixa8eIBVWYmlIKAHmjKPgnHpOXIejSrY',
    appId: '1:781512659364:web:3543534e696dd4d4037131',
    messagingSenderId: '781512659364',
    projectId: 'ewaste-6dfd4',
    authDomain: 'ewaste-6dfd4.firebaseapp.com',
    storageBucket: 'ewaste-6dfd4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7jkuPa48P-5PuH2OJhL04c5yWCMBYRE0',
    appId: '1:781512659364:android:fa26967b4fbda707037131',
    messagingSenderId: '781512659364',
    projectId: 'ewaste-6dfd4',
    storageBucket: 'ewaste-6dfd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSFoqF_LpMiStYzM1jyE5ocQBr-oESHLQ',
    appId: '1:781512659364:ios:6f7271addc574cf1037131',
    messagingSenderId: '781512659364',
    projectId: 'ewaste-6dfd4',
    storageBucket: 'ewaste-6dfd4.appspot.com',
    iosBundleId: 'com.example.plastic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSFoqF_LpMiStYzM1jyE5ocQBr-oESHLQ',
    appId: '1:781512659364:ios:114f16f176c1ec05037131',
    messagingSenderId: '781512659364',
    projectId: 'ewaste-6dfd4',
    storageBucket: 'ewaste-6dfd4.appspot.com',
    iosBundleId: 'com.example.plastic.RunnerTests',
  );
}
